
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = minres.c minresqlp.c
SOURCEF  =
SOURCEH  = minresimpl.h
LIBBASE  = libpetscksp
LOCDIR   = src/ksp/ksp/impls/minres/
MANSEC   = KSP

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
