
ALL: lib

DIRS     = richardson newton genbroyden
LOCDIR   = src/msnes/impls/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test


