ALL: lib

CPPFLAGS =
CFLAGS   =
FFLAGS   =
SOURCEC  = picell.c
SOURCEF  =
SOURCEH  =
DIRS     = 
LIBBASE  = libpetscdm
MANSEC   = DM
SUBMANSEC= DMPICELL
LOCDIR   = src/dm/impls/picell/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
