#requiresdefine 'PETSC_HAVE_VIENNACL'
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCECXX = pipecgviennacl.cxx
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscksp
DIRS     =
MANSEC   = PC
LOCDIR   = src/ksp/pc/impls/pipecgviennacl/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
