ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = linesearchbtsd.c
SOURCEF  =
SOURCEH  = 
LIBBASE  = libpetscsnes
MANSEC   = SNES
LOCDIR   = src/snes/linesearch/impls/btsd/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
