
ALL: lib

DIRS     = dense aij shell baij adj maij taij is sbaij normal lrc scatter blockmat composite cufft mffd transpose python submat localref nest fft elemental
LOCDIR   = src/mat/impls/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
