
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = newton.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscmsnes
MANSEC   = SNES
LOCDIR   = src/msnes/impls/newton/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

