#requirespackage   'PETSC_HAVE_TBB'

ALL: lib

CFLAGS   =
FFLAGS   =
CXXFLAGS =
SOURCECXX = tctbb.cxx
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscsys
MANSEC   = PetscThreadComm
LOCDIR   = src/sys/threadcomm/impls/tbb/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
