
ALL: lib

SOURCEH  = ../../include/petsc/private/snesimpl.h ../../include/petscsnes.h
DIRS     = interface impls
LOCDIR   = src/msnes/
MANSEC   = SNES

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

