#
ALL: lib

CFLAGS   =
FFLAGS   =
CPPFLAGS =
SOURCEC  = crcoarsen.c
SOURCEH  =
LIBBASE  = libpetscmat
LOCDIR   = src/mat/coarsen/impls/cr/
MANSEC   = MatOrderings

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
