ALL: lib

#requirespackage  'PETSC_HAVE_ZOLTAN'

CFLAGS   =
FFLAGS   =
SOURCEC  = zoltancolor.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscmat
MANSEC   = MatOrderings
LOCDIR   = src/mat/color/impls/zoltan/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
