ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = mad.c
SOURCEF  =
SOURCEH  = mad.h
LIBBASE  = libpetsctao
MANSEC   = Tao
LOCDIR   = src/tao/constrained/impls/mad/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

