ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = linesearcharmijo.c
SOURCEF  =
SOURCEH  = armijoimpls.h
LIBBASE  = libpetscsnes
MANSEC   = SNES
LOCDIR   = src/snes/linesearch/impls/armijo/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
