
ALL: lib

LIBBASE  = libpetscdm
DIRS     = da mapped shell
LOCDIR   = src/dm/field/impls

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
