
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = minresqlp.c
SOURCEF  =
OBJSC    = $(SOURCEC:.c=.o)
OBJSF    =
LIBBASE  = libpetscksp
LOCDIR   = src/ksp/ksp/impls/minresqlp/
MANSEC   = KSP

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
