

ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = matelementlist.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscmat
MANSEC   = Mat
DIRS     =
LOCDIR   = src/mat/impls/elementlist/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
