static char help[] = "Second Order Finite Volume Example of Laplacian div \alpha grad u = f.\n";
/*F

  Multigrid Poisson solver:
     Laplace(u) = f

  A numerical test on page 64 of
    `A MULTIGRID TUTORIAL by Briggs, Henson & McCormick'
  u := (x^2-x^4)*(y^4-y^2)*(z^4-z^2) with alpha(x) = -1

  Course grid mesh is read in from an ExodusII file, usually generated by Cubit.
F*/
#include <petscts.h>
#include <petscdmplex.h>
#include <petscdmda.h>

#define MAX_DIM 3                  /* Geometric dimension */
#define ALEN(a) (sizeof(a)/sizeof((a)[0]))

/* Represents continuum physical equations. */
typedef struct _n_Physics *Physics;

/* Physical model includes boundary conditions, initial conditions, and functionals of interest. It is
 * discretization-independent, but its members depend on the scenario being solved. */
typedef struct _n_Model *Model;

/* 'User' implements a discretization of a continuous model. */
typedef struct _n_User *User;

typedef PetscErrorCode (*SolutionFunction)(Model,PetscReal,const PetscReal*,PetscScalar*,void*);
typedef PetscErrorCode (*FunctionalFunction)(Model,PetscReal,const PetscReal*,const PetscScalar*,PetscReal*,void*);
static PetscErrorCode ModelSolutionSetDefault(Model,SolutionFunction,void*);
static PetscErrorCode ModelSourceSetDefault(Model,SolutionFunction,void*);
static PetscErrorCode ModelAlphaSetDefault(Model,SolutionFunction,void*);
static PetscErrorCode ModelFunctionalRegister(Model,const char*,PetscInt*,FunctionalFunction,void*);
static PetscErrorCode OutputVTK(DM,const char*,PetscViewer*);

struct FieldDescription {
  const char *name;
  PetscInt dof;
};

typedef struct _n_FunctionalLink *FunctionalLink;
struct _n_FunctionalLink {
  char               *name;
  FunctionalFunction func;
  void               *ctx;
  PetscInt           offset;
  FunctionalLink     next;
};

struct _n_Physics {
  PetscInt        dof;          /* number of degrees of freedom per cell */
  void            *data;
  PetscInt        nfields;
  const struct FieldDescription *field_desc;
};

struct _n_Model {
  MPI_Comm         comm;        /* Does not do collective communicaton, but some error conditions can be collective */
  Physics          physics;
  FunctionalLink   functionalRegistry;
  PetscInt         maxComputed;
  PetscInt         numMonitored;
  FunctionalLink   *functionalMonitored;
  PetscInt         numCall;
  FunctionalLink   *functionalCall;
  SolutionFunction solution;
  SolutionFunction source;
  SolutionFunction alpha;
  /* void             *solutionctx; */
  PetscInt         dim;
  PetscReal        BCFactor;
};
#define MAX_LEVEL 16
struct _n_User {
  PetscInt       numGhostCells;
  PetscInt       cEndInterior; /* First boundary process ghost cell */
  Vec            cellgeom, facegeom;
  PetscInt       vtkInterval;   /* For monitor */
  Model          model;
  PetscReal      errorInf[MAX_LEVEL]; /* stuff for each level */
  PetscReal      error2[MAX_LEVEL];
  PetscReal      dx[MAX_LEVEL][MAX_DIM]; /* dx at each level, cartisian grid */
  /* PetscInt       N[MAX_LEVEL][MAX_DIM]; */   /* number of cells in each dim */
  PetscInt       ilev; /* cache of current level */
  PetscBool      useBoxStencil;
};

/* this is going away !!!! */
typedef struct {
  PetscScalar normal[MAX_DIM];              /* Area-scaled normals */
  PetscScalar centroid[MAX_DIM];            /* Location of centroid (quadrature point) */
} FaceGeom;
typedef struct {
  PetscScalar centroid[MAX_DIM];
  PetscScalar volume;
} CellGeom;

PETSC_STATIC_INLINE PetscScalar DotD(PetscInt DIM, const PetscScalar *x, const PetscScalar *y) {PetscScalar sum = 0.0; PetscInt d; for (d = 0; d < DIM; ++d) sum += x[d]*y[d]; return sum;}
PETSC_STATIC_INLINE PetscReal Norm2D(PetscInt DIM, const PetscScalar *x) {return PetscSqrtReal(PetscAbsScalar(DotD(DIM,x,x)));}
PETSC_STATIC_INLINE void axD(PetscInt DIM, const PetscScalar a,PetscScalar *x){PetscInt i; for (i=0; i<DIM; i++) x[i] *= a;}
/* PETSC_STATIC_INLINE void waxD(PetscInt DIM, const PetscScalar a,const PetscScalar *x, PetscScalar *w){PetscInt i; for (i=0; i<DIM; i++) w[i] = x[i]*a;} */
/* PETSC_STATIC_INLINE void NormalizeD(PetscInt DIM, PetscScalar *x) {PetscReal a = 1./Norm2D(DIM,x); PetscInt d; for (d = 0; d < DIM; ++d) x[d] *= a;} */
PETSC_STATIC_INLINE void WaxpyD(PetscInt DIM, PetscScalar a, const PetscScalar *x, const PetscScalar *y, PetscScalar *w) {PetscInt d; for (d = 0; d < DIM; ++d) w[d] = a*x[d] + y[d];}

/******************* Laplacian ********************/
typedef struct {
  struct {
    PetscInt Error;
  } functional;
} Physics_Lap;

static const struct FieldDescription PhysicsFields_Lap[] = {{"U",1},{NULL,0}};

/* U: (x^2-x^4)*(y^4-y^2)*(z^4-z^2) */
#undef __FUNCT__
#define __FUNCT__ "PhysicsSolution_Lap_x4_x2"
static PetscErrorCode PhysicsSolution_Lap_x4_x2(Model mod,PetscReal time,const PetscReal *x,PetscScalar *u,void *ctx)
{
  /* Physics        phys    = (Physics)ctx; */
  /* Physics_Lap *lap = (Physics_Lap*)phys->data; */
  PetscScalar r;
  PetscScalar e[MAX_DIM];
  PetscInt d;

  PetscFunctionBeginUser;
  for (d = 0; d < mod->dim; ++d) e[d] = x[d]*x[d];
  for (d = 0; d < mod->dim; ++d) e[d] *= 1 - e[d];
  for (r = 1.0, d = 0; d < mod->dim; ++d) r *= e[d];
  u[0] = r;
  PetscFunctionReturn(0);
}

/* RHS: Lap((x^2-x^4)*(y^4-y^2)*(z^4-z^2)) */
#undef __FUNCT__
#define __FUNCT__ "PhysicsSource_Lap_x4_x2"
static PetscErrorCode PhysicsSource_Lap_x4_x2(Model mod,PetscReal time,const PetscReal *x,PetscScalar *rhs,void *ctx)
{
  /* Physics        phys    = (Physics)ctx; */
  /* Physics_Lap *lap = (Physics_Lap*)phys->data; */
  PetscScalar r;
  PetscScalar x2[MAX_DIM]; /* = x*x; */
  PetscScalar a[MAX_DIM]; /* = x2*(1-x2) */
  PetscScalar b[MAX_DIM]; /* = 2-12*x2; */
  PetscInt d;

  PetscFunctionBeginUser;
  for (d = 0; d < mod->dim; ++d) x2[d] = x[d]*x[d];
  for (d = 0; d < mod->dim; ++d) a[d] = x2[d]*(1-x2[d]);
  for (d = 0; d < mod->dim; ++d) b[d] = 2-12*x2[d];

  /* cross products of coordinates prevents the use of D_TERM */
  if (mod->dim==2)
    r = b[0]*a[1] + a[0]*b[1];
  else if (mod->dim==3)
    r = b[0]*a[1]*a[2] + a[0]*b[1]*a[2] + a[0]*a[1]*b[2];
  else  if (mod->dim==1)
   r = b[0];
  else
    SETERRQ1(PETSC_COMM_SELF,PETSC_ERR_SUP,"No support for solution this DIM %d",mod->dim);
  rhs[0] = -r; /* keep solution positive */
  PetscFunctionReturn(0);
}
#undef __FUNCT__
#define __FUNCT__ "PhysicsAlpha_n1"
static PetscErrorCode PhysicsAlpha_n1(Model mod,PetscReal time,const PetscReal *x,PetscScalar *alpha,void *ctx)
{
  /* Physics        phys    = (Physics)ctx; */
  /* Physics_Lap *lap = (Physics_Lap*)phys->data; */
  PetscFunctionBeginUser;
  alpha[0] = -1.0;
  PetscFunctionReturn(0);
}
#undef __FUNCT__
#define __FUNCT__ "PhysicsFunctional_Error"
static PetscErrorCode PhysicsFunctional_Error(Model mod,PetscReal time,const PetscScalar *x,const PetscScalar *u,PetscReal *f,void *ctx)
{
  Physics        phys    = (Physics)ctx;
  Physics_Lap   *lap = (Physics_Lap*)phys->data;
  PetscScalar    yexact[1];
  PetscErrorCode ierr;

  PetscFunctionBeginUser;
  ierr = (*mod->solution)(mod,time,x,yexact,phys);CHKERRQ(ierr);
  /* f[lap->functional.Error] = PetscAbsScalar(u[0]-yexact[0]); */
  f[lap->functional.Error] = PetscRealPart(u[0]-yexact[0]); /* lets do real error for plotting */
  PetscFunctionReturn(0);
}

#undef __FUNCT__
#define __FUNCT__ "PhysicsCreate_Lap"
static PetscErrorCode PhysicsCreate_Lap(Model mod,Physics phys)
{
  Physics_Lap *lap;
  PetscErrorCode ierr;

  PetscFunctionBeginUser;
  phys->field_desc = PhysicsFields_Lap;
  ierr = PetscNew(Physics_Lap,&phys->data);CHKERRQ(ierr);
  lap = (Physics_Lap*)phys->data;

  {
    /* Initial/transient solution with default boundary conditions */
    ierr = ModelSolutionSetDefault(mod,PhysicsSolution_Lap_x4_x2,phys);CHKERRQ(ierr);
    ierr = ModelSourceSetDefault(mod,PhysicsSource_Lap_x4_x2,phys);CHKERRQ(ierr);
    ierr = ModelAlphaSetDefault(mod,PhysicsAlpha_n1,phys);CHKERRQ(ierr);
    /* Register "canned" functionals */
    ierr = ModelFunctionalRegister(mod,"error",&lap->functional.Error,PhysicsFunctional_Error,phys);CHKERRQ(ierr);
  }
  PetscFunctionReturn(0);
}

#undef __FUNCT__
#define __FUNCT__ "ConstructGeometry"
/* Set up face data and cell volums, normals, ... */
PetscErrorCode ConstructGeometry(DM dm, Vec *facegeom, Vec *cellgeom, User user)
{
  DM             dmFace, dmCell;
  DMLabel        ghostLabel;
  PetscSection   sectionFace, sectionCell;
  PetscSection   coordSection;
  Vec            coordinates;
  PetscScalar    *fgeom, *cgeom;
  PetscInt       dim, cStart, cEnd, c, fStart, fEnd, f;
  PetscErrorCode ierr;

  PetscFunctionBeginUser;
  ierr = DMPlexGetDimension(dm, &dim);CHKERRQ(ierr);

  ierr = DMGetCoordinateSection(dm, &coordSection);CHKERRQ(ierr);
  ierr = DMGetCoordinatesLocal(dm, &coordinates);CHKERRQ(ierr);

  /* Make cell centroids and volumes */
  ierr = DMClone(dm, &dmCell);CHKERRQ(ierr);
  ierr = DMSetCoordinateSection(dmCell, coordSection);CHKERRQ(ierr);
  ierr = DMSetCoordinatesLocal(dmCell, coordinates);CHKERRQ(ierr);
  ierr = PetscSectionCreate(PetscObjectComm((PetscObject)dm), &sectionCell);CHKERRQ(ierr);
  ierr = DMDAGetHeightStratum(dm, 0, &cStart, &cEnd);CHKERRQ(ierr);
  ierr = PetscSectionSetChart(sectionCell, cStart, cEnd);CHKERRQ(ierr);
  for (c = cStart; c < cEnd; ++c) {
    ierr = PetscSectionSetDof(sectionCell, c, sizeof(CellGeom)/sizeof(PetscScalar));CHKERRQ(ierr);
  }
  ierr = PetscSectionSetUp(sectionCell);CHKERRQ(ierr);
  ierr = DMSetDefaultSection(dmCell, sectionCell);CHKERRQ(ierr);
  ierr = PetscSectionDestroy(&sectionCell);CHKERRQ(ierr); /* relinquish our reference */

  ierr = DMCreateLocalVector(dmCell, cellgeom);CHKERRQ(ierr);
  ierr = VecGetArray(*cellgeom, &cgeom);CHKERRQ(ierr);
  for (c = cStart; c < user->cEndInterior; ++c) {
    CellGeom *cg;

    ierr = DMPlexPointLocalRef(dmCell, c, cgeom, &cg);CHKERRQ(ierr);
    ierr = PetscMemzero(cg,sizeof(*cg));CHKERRQ(ierr);
    ierr = DMPlexComputeCellGeometryFVM(dmCell, c, &cg->volume, cg->centroid, NULL);CHKERRQ(ierr);
  }
  /* Compute face normals, centroid(used?) */
  ierr = DMClone(dm, &dmFace);CHKERRQ(ierr);
  ierr = PetscSectionCreate(PetscObjectComm((PetscObject)dm), &sectionFace);CHKERRQ(ierr);
  ierr = DMDAGetHeightStratum(dm, 1, &fStart, &fEnd);CHKERRQ(ierr);
  ierr = PetscSectionSetChart(sectionFace, fStart, fEnd);CHKERRQ(ierr);

  for (f = fStart; f < fEnd; ++f) {
    ierr = PetscSectionSetDof(sectionFace, f, sizeof(FaceGeom)/sizeof(PetscScalar));CHKERRQ(ierr);
  }
  ierr = PetscSectionSetUp(sectionFace);CHKERRQ(ierr);
  ierr = DMSetDefaultSection(dmFace, sectionFace);CHKERRQ(ierr);
  ierr = PetscSectionDestroy(&sectionFace);CHKERRQ(ierr);
  ierr = DMCreateLocalVector(dmFace, facegeom);CHKERRQ(ierr);
  ierr = VecGetArray(*facegeom, &fgeom);CHKERRQ(ierr);
  ierr = DMPlexGetLabel(dm, "ghost", &ghostLabel);CHKERRQ(ierr);
  for (f = fStart; f < fEnd; ++f) {
    FaceGeom *fg;
    PetscInt  ghost;

    ierr = DMLabelGetValue(ghostLabel, f, &ghost);CHKERRQ(ierr);
    if (ghost >= 0) continue;
    ierr = DMPlexPointLocalRef(dmFace, f, fgeom, &fg);CHKERRQ(ierr);
    ierr = DMPlexComputeCellGeometryFVM(dm, f, NULL, fg->centroid, fg->normal);CHKERRQ(ierr);
    /* Flip face orientation if necessary to match ordering in support, and Update minimum radius */
    {
      CellGeom       *cL, *cR;
      const PetscInt *cells;
      PetscReal      *lcentroid, *rcentroid;
      PetscScalar     v[3];
      PetscInt        d;

      ierr = DMPlexGetSupport(dm, f, &cells);CHKERRQ(ierr);
      ierr = DMPlexPointLocalRead(dmCell, cells[0], cgeom, &cL);CHKERRQ(ierr);
      ierr = DMPlexPointLocalRead(dmCell, cells[1], cgeom, &cR);CHKERRQ(ierr);
      lcentroid = cells[0] >= user->cEndInterior ? fg->centroid : cL->centroid;
      rcentroid = cells[1] >= user->cEndInterior ? fg->centroid : cR->centroid;
      WaxpyD(user->model->dim,-1, lcentroid, rcentroid, v);
      if (DotD(user->model->dim,fg->normal, v) < 0) {
        for (d = 0; d < dim; ++d) fg->normal[d] = -fg->normal[d];
      }
      if (DotD(user->model->dim,fg->normal, v) <= 0) {
        if (dim == 2)SETERRQ5(PETSC_COMM_SELF,PETSC_ERR_PLIB,"Direction for face %d could not be fixed, normal (%g,%g) v (%g,%g)", f, fg->normal[0], fg->normal[1], v[0], v[1]);
        else if (dim == 3) SETERRQ7(PETSC_COMM_SELF,PETSC_ERR_PLIB,"Direction for face %d could not be fixed, normal (%g,%g,%g) v (%g,%g,%g)", f, fg->normal[0], fg->normal[1], fg->normal[2], v[0], v[1], v[2]);
      }
    }
  }
  /* Compute centroids of ghost cells */
  for (c = user->cEndInterior; c < cEnd; ++c) {
    FaceGeom       *fg;
    const PetscInt *cone,    *support;
    PetscInt        coneSize, supportSize, s;

    ierr = DMPlexGetConeSize(dmCell, c, &coneSize);CHKERRQ(ierr);
    if (coneSize != 1) SETERRQ2(PETSC_COMM_SELF, PETSC_ERR_ARG_WRONG, "Ghost cell %d has cone size %d != 1", c, coneSize);
    ierr = DMPlexGetCone(dmCell, c, &cone);CHKERRQ(ierr);
    ierr = DMPlexGetSupportSize(dmCell, cone[0], &supportSize);CHKERRQ(ierr);
    if (supportSize != 2) SETERRQ2(PETSC_COMM_SELF, PETSC_ERR_ARG_WRONG, "Face %d has support size %d != 1", cone[0], supportSize);
    ierr = DMPlexGetSupport(dmCell, cone[0], &support);CHKERRQ(ierr);
    ierr = DMPlexPointLocalRef(dmFace, cone[0], fgeom, &fg);CHKERRQ(ierr);
    for (s = 0; s < 2; ++s) {
      /* Reflect ghost centroid across plane of face */
      if (support[s] == c) {
        const CellGeom *ci;
        CellGeom       *cg;
        PetscScalar     c2f[3], a;

        ierr = DMPlexPointLocalRead(dmCell, support[(s+1)%2], cgeom, &ci);CHKERRQ(ierr);
        WaxpyD(user->model->dim,-1, ci->centroid, fg->centroid, c2f); /* cell to face centroid */
        a    = DotD(user->model->dim,c2f, fg->normal)/DotD(user->model->dim,fg->normal, fg->normal);
        ierr = DMPlexPointLocalRef(dmCell, support[s], cgeom, &cg);CHKERRQ(ierr);
        WaxpyD(user->model->dim,2*a, fg->normal, ci->centroid, cg->centroid);
        cg->volume = ci->volume;
      }
    }
  }
  ierr = VecRestoreArray(*facegeom, &fgeom);CHKERRQ(ierr);
  ierr = VecRestoreArray(*cellgeom, &cgeom);CHKERRQ(ierr);
  ierr = DMDestroy(&dmCell);CHKERRQ(ierr);
  ierr = DMDestroy(&dmFace);CHKERRQ(ierr);
  PetscFunctionReturn(0);
}

#undef __FUNCT__
#define __FUNCT__ "ModelSolutionSetDefault"
static PetscErrorCode ModelSolutionSetDefault(Model mod,SolutionFunction func,void *ctx)
{
  PetscFunctionBeginUser;
  mod->solution    = func;
  /* mod->solutionctx = ctx; */
  PetscFunctionReturn(0);
}
#undef __FUNCT__
#define __FUNCT__ "ModelSourceSetDefault"
static PetscErrorCode ModelSourceSetDefault(Model mod,SolutionFunction func,void *ctx)
{
  PetscFunctionBeginUser;
  mod->source    = func;
  /* mod->solutionctx = ctx; */
  PetscFunctionReturn(0);
}
#undef __FUNCT__
#define __FUNCT__ "ModelAlphaSetDefault"
static PetscErrorCode ModelAlphaSetDefault(Model mod,SolutionFunction func,void *ctx)
{
  PetscFunctionBeginUser;
  mod->alpha    = func;
  /* mod->solutionctx = ctx; */
  PetscFunctionReturn(0);
}

#undef __FUNCT__
#define __FUNCT__ "ModelFunctionalRegister"
static PetscErrorCode ModelFunctionalRegister(Model mod,const char *name,PetscInt *offset,FunctionalFunction func,void *ctx)
{
  PetscErrorCode ierr;
  FunctionalLink link,*ptr;
  PetscInt       lastoffset = -1;

  PetscFunctionBeginUser;
  for (ptr=&mod->functionalRegistry; *ptr; ptr = &(*ptr)->next) lastoffset = (*ptr)->offset;
  ierr         = PetscNew(struct _n_FunctionalLink,&link);CHKERRQ(ierr);
  ierr         = PetscStrallocpy(name,&link->name);CHKERRQ(ierr);
  link->offset = lastoffset + 1;
  link->func   = func;
  link->ctx    = ctx;
  link->next   = NULL;
  *ptr         = link;
  *offset      = link->offset;
  PetscFunctionReturn(0);
}

#undef __FUNCT__
#define __FUNCT__ "ModelFunctionalSetFromOptions"
static PetscErrorCode ModelFunctionalSetFromOptions(Model mod)
{
  PetscErrorCode ierr;
  PetscInt       i,j;
  FunctionalLink link;
  char           *names[256];

  PetscFunctionBeginUser;
  mod->numMonitored = ALEN(names);
  ierr = PetscOptionsStringArray("-monitor","list of functionals to monitor","",names,&mod->numMonitored,NULL);CHKERRQ(ierr);
  /* Create list of functionals that will be computed somehow */
  ierr = PetscMalloc(mod->numMonitored*sizeof(FunctionalLink),&mod->functionalMonitored);CHKERRQ(ierr);
  /* Create index of calls that we will have to make to compute these functionals (over-allocation in general). */
  ierr = PetscMalloc(mod->numMonitored*sizeof(FunctionalLink),&mod->functionalCall);CHKERRQ(ierr);
  mod->numCall = 0;

  for (i=0; i<mod->numMonitored; i++) {
    for (link=mod->functionalRegistry; link; link=link->next) {
      PetscBool match;
      ierr = PetscStrcasecmp(names[i],link->name,&match);CHKERRQ(ierr);
      if (match) break;
    }
    if (!link) SETERRQ1(mod->comm,PETSC_ERR_USER,"No known functional '%s'",names[i]);
    mod->functionalMonitored[i] = link;
    for (j=0; j<i; j++) {
      if (mod->functionalCall[j]->func == link->func && mod->functionalCall[j]->ctx == link->ctx) goto next_name;
    }
    mod->functionalCall[mod->numCall++] = link; /* Just points to the first link using the result. There may be more results. */
next_name:
    ierr = PetscFree(names[i]);CHKERRQ(ierr);
  }

  /* Find out the maximum index of any functional computed by a function we will be calling (even if we are not using it) */
  mod->maxComputed = -1;
  for (link=mod->functionalRegistry; link; link=link->next) {
    for (i=0; i<mod->numCall; i++) {
      FunctionalLink call = mod->functionalCall[i];
      if (link->func == call->func && link->ctx == call->ctx) {
        mod->maxComputed = PetscMax(mod->maxComputed,link->offset);
      }
    }
  }
  PetscFunctionReturn(0);
}

#undef __FUNCT__
#define __FUNCT__ "FunctionalLinkDestroy"
static PetscErrorCode FunctionalLinkDestroy(FunctionalLink *link)
{
  PetscErrorCode ierr;
  FunctionalLink l,next;

  PetscFunctionBeginUser;
  if (!link) PetscFunctionReturn(0);
  l     = *link;
  *link = NULL;
  for (; l; l=next) {
    next = l->next;
    ierr = PetscFree(l->name);CHKERRQ(ierr);
    ierr = PetscFree(l);CHKERRQ(ierr);
  }
  PetscFunctionReturn(0);
}

#undef __FUNCT__
#define __FUNCT__ "SetInitialCondition"
PetscErrorCode SetInitialCondition(DM dm, Vec X, User user)
{
  PetscScalar       *x;
  PetscInt          cStart, cEnd, cEndInterior = user->cEndInterior, c;
  PetscErrorCode    ierr;

  PetscFunctionBeginUser;
  ierr = DMDAGetHeightStratum(dm, 0, &cStart, &cEnd);CHKERRQ(ierr);
  ierr = VecGetArray(X, &x);CHKERRQ(ierr);
  for (c = cStart; c < cEndInterior; ++c) {
    PetscScalar    *xc;
    ierr = DMPlexPointGlobalRef(dm,c,x,&xc);CHKERRQ(ierr);
    if (xc) *xc = 0.; /* process ghost */
  }
  ierr = VecRestoreArray(X, &x);CHKERRQ(ierr);
  PetscFunctionReturn(0);
}

#undef __FUNCT__
#define __FUNCT__ "OutputVTK"
static PetscErrorCode OutputVTK(DM dm, const char *filename, PetscViewer *viewer)
{
  PetscErrorCode ierr;

  PetscFunctionBeginUser;
  ierr = PetscViewerCreate(PetscObjectComm((PetscObject)dm), viewer);CHKERRQ(ierr);
  ierr = PetscViewerSetType(*viewer, PETSCVIEWERVTK);CHKERRQ(ierr);
  ierr = PetscViewerFileSetName(*viewer, filename);CHKERRQ(ierr);
  PetscFunctionReturn(0);
}

#undef __FUNCT__
#define __FUNCT__ "MonitorVTK"
static PetscErrorCode MonitorVTK(TS ts,PetscInt stepnum,PetscReal time,Vec X,void *ctx)
{
  User           user = (User)ctx;
  DM             dm;
  PetscViewer    viewer;
  char           filename[PETSC_MAX_PATH_LEN],*ftable = NULL;
  PetscReal      xnorm;
  Vec            E=0;
  PetscErrorCode ierr;

  PetscFunctionBeginUser;
  ierr = PetscObjectSetName((PetscObject) X, "solution");CHKERRQ(ierr);
  ierr = VecGetDM(X,&dm);CHKERRQ(ierr);
  ierr = VecNorm(X,NORM_INFINITY,&xnorm);CHKERRQ(ierr);
  ierr = VecDuplicate(X,&E);CHKERRQ(ierr);
  if (stepnum >= 0) {           /* No summary for final time */
    Model             mod = user->model;
    PetscInt          c,cStart,cEnd,fcount,i;
    size_t            ftableused,ftablealloc;
    const PetscScalar *cellgeom_v,*x_v;
    PetscScalar       *func_v;
    DM                dmCell;
    PetscReal         *fmin,*fmax,*fintegral,*ftmp;
    fcount = mod->maxComputed+1;
    ierr   = PetscMalloc4(fcount,PetscReal,&fmin,fcount,PetscReal,&fmax,fcount,PetscReal,&fintegral,fcount,PetscReal,&ftmp);CHKERRQ(ierr);
    for (i=0; i<fcount; i++) {
      fmin[i]      = PETSC_MAX_REAL;
      fmax[i]      = PETSC_MIN_REAL;
      fintegral[i] = 0;
    }
    ierr = DMDAGetHeightStratum(dm,0,&cStart,&cEnd);CHKERRQ(ierr);
    ierr = VecGetDM(user->cellgeom,&dmCell);CHKERRQ(ierr);
    ierr = VecGetArrayRead(user->cellgeom,&cellgeom_v);CHKERRQ(ierr);
    ierr = VecGetArrayRead(X,&x_v);CHKERRQ(ierr);
    ierr = VecGetArray(E,&func_v);CHKERRQ(ierr);
    for (c=cStart; c<user->cEndInterior; c++) {
      const CellGeom    *cg;
      const PetscScalar *cx;
      PetscScalar *cfunc;
      ierr = DMPlexPointLocalRead(dmCell,c,cellgeom_v,&cg);CHKERRQ(ierr);
      ierr = DMPlexPointGlobalRead(dm,c,x_v,&cx);CHKERRQ(ierr);
      ierr = DMPlexPointGlobalRef(dm,c,func_v,&cfunc);CHKERRQ(ierr);
      if (!cx) continue;        /* not a global cell */
      for (i=0; i<mod->numCall; i++) {
        FunctionalLink flink = mod->functionalCall[i];
        ierr = (*flink->func)(mod,time,cg->centroid,cx,&ftmp[i],flink->ctx);CHKERRQ(ierr);
        *cfunc = ftmp[i]; /* save last functional */
        if (i==mod->numCall-1) ftmp[i] = PetscAbs(ftmp[i]); /* allready a real, this assumes we want an abs - error */
      }
      for (i=0; i<fcount; i++) {
        fmin[i]       = PetscMin(fmin[i],ftmp[i]);
        fmax[i]       = PetscMax(fmax[i],ftmp[i]);
        fintegral[i] += cg->volume * ftmp[i];
      }
    }
    ierr = VecRestoreArrayRead(user->cellgeom,&cellgeom_v);CHKERRQ(ierr);
    ierr = VecRestoreArrayRead(X,&x_v);CHKERRQ(ierr);
    ierr = VecRestoreArray(E,&func_v);CHKERRQ(ierr);
    ierr = MPI_Allreduce(MPI_IN_PLACE,fmin,fcount,MPIU_REAL,MPI_MIN,PetscObjectComm((PetscObject)ts));CHKERRQ(ierr);
    ierr = MPI_Allreduce(MPI_IN_PLACE,fmax,fcount,MPIU_REAL,MPI_MAX,PetscObjectComm((PetscObject)ts));CHKERRQ(ierr);
    ierr = MPI_Allreduce(MPI_IN_PLACE,fintegral,fcount,MPIU_REAL,MPI_SUM,PetscObjectComm((PetscObject)ts));CHKERRQ(ierr);
    if (fcount) { user->errorInf[user->ilev] = fmax[mod->numCall-1]; user->error2[user->ilev] = fintegral[mod->numCall-1]; } /* keep for convergence test */
    ftablealloc = fcount * 100;
    ftableused  = 0;
    ierr        = PetscMalloc(ftablealloc,&ftable);CHKERRQ(ierr);
    for (i=0; i<mod->numMonitored; i++) {
      size_t         countused;
      char           buffer[256],*p;
      FunctionalLink flink = mod->functionalMonitored[i];
      PetscInt       id    = flink->offset;
      if (i % 3) {
        ierr = PetscMemcpy(buffer,"  ",2);CHKERRQ(ierr);
        p    = buffer + 2;
      } else if (i) {
        char newline[] = "\n";
        ierr = PetscMemcpy(buffer,newline,sizeof newline-1);CHKERRQ(ierr);
        p    = buffer + sizeof newline - 1;
      } else {
        p = buffer;
      }
      ierr = PetscSNPrintfCount(p,sizeof buffer-(p-buffer),"%12s functional: [%10.7G,%10.7G] integral=%10.7G",&countused,flink->name,fmin[id],fmax[id],fintegral[id]);CHKERRQ(ierr);
      countused += p - buffer;
      if (countused > ftablealloc-ftableused-1) { /* reallocate */
        char *ftablenew;
        ftablealloc = 2*ftablealloc + countused;
        ierr = PetscMalloc(ftablealloc,&ftablenew);CHKERRQ(ierr);
        ierr = PetscMemcpy(ftablenew,ftable,ftableused);CHKERRQ(ierr);
        ierr = PetscFree(ftable);CHKERRQ(ierr);
        ftable = ftablenew;
      }
      ierr = PetscMemcpy(ftable+ftableused,buffer,countused);CHKERRQ(ierr);
      ftableused += countused;
      ftable[ftableused] = 0;
    }
    ierr = PetscFree4(fmin,fmax,fintegral,ftmp);CHKERRQ(ierr);

    ierr = PetscPrintf(PetscObjectComm((PetscObject)ts),"% 3D  time %8.4G  |x| %8.4G  %s\n",stepnum,time,xnorm,ftable ? ftable : "");CHKERRQ(ierr);
    ierr = PetscFree(ftable);CHKERRQ(ierr);
  }
  if (user->vtkInterval < 1) {
    ierr = VecDestroy(&E);CHKERRQ(ierr);
    PetscFunctionReturn(0);
  }
  if (user->model->functionalCall && ((stepnum == -1) ^ (stepnum % user->vtkInterval == 0))) {
    Model          mod   = user->model;
    FunctionalLink flink = mod->functionalCall[mod->numCall-1];
    if (stepnum == -1) {        /* Final time is not multiple of normal time interval, write it anyway */
      ierr = TSGetTimeStepNumber(ts,&stepnum);CHKERRQ(ierr);
    }
    ierr = PetscSNPrintf(filename,sizeof filename,"ex99-%03D-u.vtu",stepnum);CHKERRQ(ierr);
    ierr = OutputVTK(dm,filename,&viewer);CHKERRQ(ierr);
    ierr = VecView(X,viewer);CHKERRQ(ierr);
    ierr = PetscViewerDestroy(&viewer);CHKERRQ(ierr);
    ierr = PetscObjectSetName((PetscObject) E, flink->name);CHKERRQ(ierr);
    ierr = PetscSNPrintf(filename,sizeof filename,"ex99-%03D-%s.vtu",stepnum,flink->name);CHKERRQ(ierr);
    ierr = OutputVTK(dm,filename,&viewer);CHKERRQ(ierr);
    ierr = VecView(E,viewer);CHKERRQ(ierr);
    ierr = PetscViewerDestroy(&viewer);CHKERRQ(ierr);
  }
  ierr = VecDestroy(&E);CHKERRQ(ierr);
  PetscFunctionReturn(0);
}

#undef __FUNCT__
#define __FUNCT__ "CreatePartitionVec"
PetscErrorCode CreatePartitionVec(DM dm, DM *dmCell, Vec *partition)
{
  PetscSF        sfPoint;
  PetscSection   coordSection;
  Vec            coordinates;
  PetscSection   sectionCell;
  PetscScalar    *part;
  PetscInt       cStart, cEnd, c;
  PetscMPIInt    rank;
  PetscErrorCode ierr;

  PetscFunctionBeginUser;
  ierr = DMGetCoordinateSection(dm, &coordSection);CHKERRQ(ierr);
  ierr = DMGetCoordinatesLocal(dm, &coordinates);CHKERRQ(ierr);
  ierr = DMClone(dm, dmCell);CHKERRQ(ierr);
  ierr = DMGetPointSF(dm, &sfPoint);CHKERRQ(ierr);
  ierr = DMSetPointSF(*dmCell, sfPoint);CHKERRQ(ierr);
  ierr = DMSetCoordinateSection(*dmCell, coordSection);CHKERRQ(ierr);
  ierr = DMSetCoordinatesLocal(*dmCell, coordinates);CHKERRQ(ierr);
  ierr = MPI_Comm_rank(PetscObjectComm((PetscObject)dm), &rank);CHKERRQ(ierr);
  ierr = PetscSectionCreate(PetscObjectComm((PetscObject)dm), &sectionCell);CHKERRQ(ierr);
  ierr = DMDAGetHeightStratum(*dmCell, 0, &cStart, &cEnd);CHKERRQ(ierr);
  ierr = PetscSectionSetChart(sectionCell, cStart, cEnd);CHKERRQ(ierr);
  for (c = cStart; c < cEnd; ++c) {
    ierr = PetscSectionSetDof(sectionCell, c, 1);CHKERRQ(ierr);
  }
  ierr = PetscSectionSetUp(sectionCell);CHKERRQ(ierr);
  ierr = DMSetDefaultSection(*dmCell, sectionCell);CHKERRQ(ierr);
  ierr = PetscSectionDestroy(&sectionCell);CHKERRQ(ierr);
  ierr = DMCreateLocalVector(*dmCell, partition);CHKERRQ(ierr);
  ierr = PetscObjectSetName((PetscObject)*partition, "partition");CHKERRQ(ierr);
  ierr = VecGetArray(*partition, &part);CHKERRQ(ierr);
  for (c = cStart; c < cEnd; ++c) {
    PetscScalar *p;

    ierr = DMPlexPointLocalRef(*dmCell, c, part, &p);CHKERRQ(ierr);
    p[0] = rank;
  }
  ierr = VecRestoreArray(*partition, &part);CHKERRQ(ierr);
  PetscFunctionReturn(0);
}

#undef __FUNCT__
#define __FUNCT__ "ApplyLaplacianLocal"
static PetscErrorCode ApplyLaplacianLocal(DM dm,DM dmFace,DM dmCell,PetscReal time,Vec locU,Vec F,User user)
{
  DMLabel           ghostLabel;
  PetscErrorCode    ierr;
  const PetscScalar *facegeom, *cellgeom, *uArray;
  PetscScalar       *f;
  PetscInt          fStart, fEnd, face;
  const PetscReal   sten[2]={10./12.,1./12.}; /* 1D stencil: [1  10  1] / 12 */
  const PetscReal   BCFact = user->model->BCFactor; /* Diri */
  const int dim = user->model->dim;

  PetscFunctionBeginUser;
  ierr = VecGetArrayRead(user->facegeom,&facegeom);CHKERRQ(ierr);
  ierr = VecGetArrayRead(user->cellgeom,&cellgeom);CHKERRQ(ierr);// kill
  ierr = VecGetArrayRead(locU,&uArray);CHKERRQ(ierr);
  ierr = VecGetArray(F,&f);CHKERRQ(ierr);
  ierr = DMPlexGetLabel(dm, "ghost", &ghostLabel);CHKERRQ(ierr);
  ierr = DMDAGetHeightStratum(dm, 1, &fStart, &fEnd);CHKERRQ(ierr);
  for (face = fStart; face < fEnd; ++face) {
    const PetscInt    *cells;
    PetscInt          ghost,nC,dirs[MAX_DIM],i;
    PetscScalar       *fL,*fR,area,flux,alpha,u[2];
    PetscReal          v[MAX_DIM],dx,fact0[2],fact1[2];
    const FaceGeom    *fg;
    const CellGeom    *cgL,*cgR;
    const PetscScalar *puL,*puR;

    ierr = DMLabelGetValue(ghostLabel, face, &ghost);CHKERRQ(ierr);
    if (ghost >= 0) continue;
    ierr = DMPlexPointLocalRead(dmFace,face,facegeom,&fg);CHKERRQ(ierr);
    /* get direction of face */
    for (i=0,dirs[0]=-1;i<dim;++i) if (fg->normal[i]!=0.0) dirs[0] = i;
    ierr = DMPlexGetSupportSize(dm, face, &nC);CHKERRQ(ierr);
    ierr = DMPlexGetSupport(dm, face, &cells);CHKERRQ(ierr);
    ierr = DMPlexPointLocalRead(dmCell,cells[0],cellgeom,&cgL);CHKERRQ(ierr); // kill
    ierr = DMPlexPointLocalRead(dm,cells[0],uArray,&puL);CHKERRQ(ierr);
    ierr = DMPlexPointGlobalRef(dm,cells[0],f,&fL);CHKERRQ(ierr);
    fact0[0] = fact0[1] = 1.;
    if (nC==2) {
      ierr = DMPlexPointLocalRead(dmCell,cells[1],cellgeom,&cgR);CHKERRQ(ierr); // kill
      ierr = DMPlexPointLocalRead(dm,cells[1],uArray,&puR);CHKERRQ(ierr);
      ierr = DMPlexPointGlobalRef(dm,cells[1],f,&fR);CHKERRQ(ierr);
    }
    else {
      ierr = DMPlexPointLocalRead(dmCell,cells[0],cellgeom,&cgR);CHKERRQ(ierr); // kill
      /* ierr = DMPlexPointLocalRead(dm,cells[0],uArray,&puR);CHKERRQ(ierr); */
      /* ierr = DMPlexPointGlobalRef(dm,cells[0],f,&fR);CHKERRQ(ierr); */
      puR = puL;
      fR = 0; /* no update of ghost */
      if (fg->normal[dirs[0]] > 0.) fact0[1] = BCFact; // right ghost
      else fact0[0] = BCFact;
PetscPrintf(PETSC_COMM_WORLD,"ApplyLaplacianLocal: have domain ghost cell on face %d cell %d normal %e in direction %d\n",face,cells[0],fg->normal[dirs[0]],dirs[0]);
    }
    ierr = (*user->model->alpha)(user->model,time,fg->centroid,&alpha,user->model->physics);CHKERRQ(ierr);
    if (user->useBoxStencil) { /* use a box, not start, stencil */
      int s0; /* short recursion by hand ? */
      PetscPrintf(PETSC_COMM_WORLD,"\t\tApplyLaplacianLocal: do corners: face 0 normal %e in direction %d\n",fg->normal[dirs[0]],dirs[0]);
      u[0] = fact0[0]*sten[0]*(*puL);
      u[1] = fact0[1]*sten[0]*(*puR);
      /* for each side of face 0 */
      for (s0=0;s0<2;s0++) {
        const FaceGeom *fg;
        PetscInt numFaces,f;
        const PetscInt *faces;
        const PetscInt cell= (nC==2 || s0==0) ? cells[s0] : cells[0];
        DMPlexGetConeSize(dm, cell, &numFaces);
        DMPlexGetCone(dm, cell, &faces);
        for (f = 0; f < numFaces; ++f) {
          const PetscInt face = faces[f];
          ierr = DMPlexPointLocalRead(dmFace,face,facegeom,&fg);CHKERRQ(ierr);
          for (i=0,dirs[1]=-1;i<dim;++i) if (fg->normal[i] != 0.0 && i != dirs[0]) dirs[1]=i;
          if (dirs[1]!=-1) { /* we have a perp face  */
            PetscInt nC;
            const PetscInt *cells;
            const PetscScalar *puL,*puR;
            ierr = DMPlexGetSupportSize(dm, face, &nC);CHKERRQ(ierr);
PetscPrintf(PETSC_COMM_WORLD,"\t\t\tApplyLaplacianLocal: do corners: face 1 normal %e in direction %d\n",fg->normal[dirs[1]],dirs[1]);
            ierr = DMPlexGetSupport(dm, face, &cells);CHKERRQ(ierr);
            ierr = DMPlexPointLocalRead(dm,cells[0],uArray,&puL);CHKERRQ(ierr);
            fact1[0] = fact1[1] = 1.;
            if (nC==2) {
              ierr = DMPlexPointLocalRead(dm,cells[1],uArray,&puR);CHKERRQ(ierr);
            }
            else {
              puR = puL;
              if (fg->normal[dirs[0]] > 0.) fact1[1] = BCFact; // right ghost
              else fact1[0] = BCFact;
            }
            if (dim==2) {
PetscPrintf(PETSC_COMM_WORLD,"\t\t\t\t: %d\n",fg->normal[dirs[1]],dirs[1]);
              u[0] += fact0[0]*fact1[0]*sten[1]*(*puL);
              u[1] += fact0[1]*fact1[1]*sten[1]*(*puR);
            }
            else {
              /* 3rd D */
              SETERRQ1(PETSC_COMM_WORLD,PETSC_ERR_ARG_WRONGSTATE,"dim=%d",dim);
            }
          }
        }
      }
    } else {
      u[0] = fact0[0] * (*puL); u[1] = fact0[1] * (*puR);
    }

    WaxpyD(user->model->dim,-1,cgL->centroid,cgR->centroid,v); /* dx vector -- don't need this -- no cellgeom */
    PetscPrintf(PETSC_COMM_WORLD,"\tApplyLaplacianLocal: dx vector=(%e,%e)\n",v[0],v[1]);
    dx = Norm2D(user->model->dim,v);
    if(abs(user->dx[user->ilev][0]-dx)>1.e-12) SETERRQ1(PETSC_COMM_WORLD,PETSC_ERR_ARG_WRONGSTATE,"x=%e",dx);
    area = Norm2D(user->model->dim,fg->normal);

    flux = alpha*(u[1] - u[0])/dx;
    if (fL) *fL -= area*flux / cgL->volume;
    if (fR) *fR += area*flux / cgR->volume;
  }
  ierr = VecRestoreArrayRead(user->facegeom,&facegeom);CHKERRQ(ierr);
  ierr = VecRestoreArrayRead(user->cellgeom,&cellgeom);CHKERRQ(ierr); // kill
  ierr = VecRestoreArrayRead(locU,&uArray);CHKERRQ(ierr);
  ierr = VecRestoreArray(F,&f);CHKERRQ(ierr);
  PetscFunctionReturn(0);
}

#undef __FUNCT__
#define __FUNCT__ "ComputeFunctionLap"
/*
 Finite difference operator for Jacobian.  The operator in SNES form.
 */
PetscErrorCode ComputeFunctionLap(SNES snes,Vec U,Vec FU,void *ctx)
{
  User           user = (User)ctx;
  DM             dm, dmFace, dmCell;
  Vec            locU;
  PetscErrorCode ierr;

  PetscFunctionBeginUser;
  ierr = SNESGetDM(snes,&dm);CHKERRQ(ierr);
  ierr = VecGetDM(user->facegeom,&dmFace);CHKERRQ(ierr);
  ierr = VecGetDM(user->cellgeom,&dmCell);CHKERRQ(ierr);
  ierr = DMGetLocalVector(dm,&locU);CHKERRQ(ierr);
  ierr = DMGlobalToLocalBegin(dm, U, INSERT_VALUES, locU);CHKERRQ(ierr); /* get ghost values - exchange */
  ierr = DMGlobalToLocalEnd(dm, U, INSERT_VALUES, locU);CHKERRQ(ierr);
  ierr = VecZeroEntries(FU);CHKERRQ(ierr);
  ierr = ApplyLaplacianLocal(dm,dmFace,dmCell,0.,locU,FU,user);CHKERRQ(ierr);

  ierr = DMRestoreLocalVector(dm,&locU);CHKERRQ(ierr);

  PetscFunctionReturn(0);
}

#undef __FUNCT__
#define __FUNCT__ "RHSFunctionLap"
/*
 Laplacian + Source term for TS RHS: Au - b
 */
PetscErrorCode RHSFunctionLap(TS ts,PetscReal t,Vec globalin,Vec globalout,void *ctx)
{
  PetscErrorCode ierr;
  Mat            A;
  User           user = (User)ctx;
  Model          mod = user->model;
  PetscInt       cStart, cEnd, c;
  DM             dm,dmCell;
  const PetscScalar *cgeom_v;
  PetscScalar *x_v,source[1];

  PetscFunctionBeginUser;
  ierr = TSGetRHSJacobian(ts,&A,NULL,NULL,&ctx);CHKERRQ(ierr);
  ierr = MatMult(A,globalin,globalout);CHKERRQ(ierr);
  /* subtract off RHS to solve Ax=b */
  ierr = TSGetDM(ts,&dm);CHKERRQ(ierr);
  ierr = VecGetDM(user->cellgeom, &dmCell);CHKERRQ(ierr);
  ierr = DMDAGetHeightStratum(dm, 0, &cStart, &cEnd);CHKERRQ(ierr);
  ierr = VecGetArrayRead(user->cellgeom, &cgeom_v);CHKERRQ(ierr);
  ierr = VecGetArray(globalout, &x_v);CHKERRQ(ierr);
  for (c = cStart; c < user->cEndInterior; ++c) {
    CellGeom *cg;
    PetscScalar *xc;
    ierr = DMPlexPointLocalRead(dmCell,c,cgeom_v,&cg);CHKERRQ(ierr);
    ierr = (*mod->source)(mod,t,cg->centroid,source,mod->physics);CHKERRQ(ierr);
    ierr = DMPlexPointGlobalRef(dm,c,x_v,&xc);CHKERRQ(ierr);
    if (xc) *xc -= source[0];
  }
  ierr = VecRestoreArrayRead(user->cellgeom, &cgeom_v);CHKERRQ(ierr);
  ierr = VecRestoreArray(globalout, &x_v);CHKERRQ(ierr);
  VecScale(globalout, -1.); /* why is this needed to get SNES residual correct? */
  PetscFunctionReturn(0);
}

#undef __FUNCT__
#define __FUNCT__ "main"
int main(int argc, char **argv)
{
  MPI_Comm          comm;
  User              user;
  Model             mod;
  Physics           phys;
  DM                dm;
  PetscReal         ftime,dt,L=1.;
  PetscInt          overlap, nsteps, nrefine,i,ilev, N[MAX_DIM];
  int               refinement_ratio;
  TS                ts;
  TSConvergedReason reason;
  Vec               X;
  Mat               A;
  PetscViewer       viewer;
  PetscMPIInt       rank;
  PetscBool         vtkCellGeom;
  PetscErrorCode    ierr;

  ierr = PetscInitialize(&argc, &argv, (char*) 0, help);CHKERRQ(ierr);
  comm = PETSC_COMM_WORLD;
  ierr = MPI_Comm_rank(comm, &rank);CHKERRQ(ierr);

  ierr = PetscNew(struct _n_User,&user);CHKERRQ(ierr);
  ierr = PetscNew(struct _n_Model,&user->model);CHKERRQ(ierr);
  ierr = PetscNew(struct _n_Physics,&user->model->physics);CHKERRQ(ierr);
  mod  = user->model;
  phys = mod->physics;
  mod->comm = comm;

  ierr = PetscOptionsBegin(comm,NULL,"Structured Grid Finite Volume Options","");CHKERRQ(ierr);
  {
    user->useBoxStencil = PETSC_FALSE;
    ierr = PetscOptionsBool("-use_box_stencil","Use a box (9 or 27 point) stencil","",user->useBoxStencil,&user->useBoxStencil,NULL);CHKERRQ(ierr);
    mod->dim = 2;
    ierr = PetscOptionsInt("-dim","dimension of problem (2 or 3)","",mod->dim,&mod->dim,NULL);CHKERRQ(ierr);
    for (i=0;i<MAX_DIM;i++) N[i] = 1;
    for (i=0;i<mod->dim;i++) N[i] = 4; /* default size */
    ierr = PetscOptionsInt("-nx","number of cells in x direction","",N[0],&N[0],NULL);CHKERRQ(ierr);
    ierr = PetscOptionsInt("-ny","number of cells in y direction","",N[1],&N[1],NULL);CHKERRQ(ierr);
    ierr = PetscOptionsInt("-nz","number of cells in z direction","",N[2],&N[2],NULL);CHKERRQ(ierr);
    refinement_ratio = 2;
    ierr = PetscOptionsInt("-refinement_ratio","Multigrid refimenet ratio","",refinement_ratio,&refinement_ratio,NULL);CHKERRQ(ierr);
    user->vtkInterval = 1;
    ierr = PetscOptionsInt("-ufv_vtk_interval","VTK output interval (0 to disable)","",user->vtkInterval,&user->vtkInterval,NULL);CHKERRQ(ierr);
    overlap = 1;
    ierr = PetscOptionsInt("-ufv_mesh_overlap","Number of cells to overlap partitions","",overlap,&overlap,NULL);CHKERRQ(ierr);
    vtkCellGeom = PETSC_FALSE;
    nrefine=0;
    ierr = PetscOptionsInt("-nrefine","Number of refinment steps","",nrefine,&nrefine,NULL);CHKERRQ(ierr);
    if (nrefine>=MAX_LEVEL) nrefine = MAX_LEVEL-1;
    ierr = PetscOptionsBool("-ufv_vtk_cellgeom","Write cell geometry (for debugging)","",vtkCellGeom,&vtkCellGeom,NULL);CHKERRQ(ierr);
    ierr = PetscMemzero(phys,sizeof(struct _n_Physics));CHKERRQ(ierr);
    ierr = PhysicsCreate_Lap(mod,phys);CHKERRQ(ierr);
    /* Count number of fields and dofs */
    for (phys->nfields=0,phys->dof=0; phys->field_desc[phys->nfields].name; phys->nfields++) phys->dof += phys->field_desc[phys->nfields].dof;
    if (phys->dof != 1) SETERRQ1(comm,PETSC_ERR_ARG_WRONGSTATE,"Physics dof=%d",phys->dof);
    mod->BCFactor = -1.0; /* Diri */
    ierr = ModelFunctionalSetFromOptions(mod);CHKERRQ(ierr);
  }
  ierr = PetscOptionsEnd();CHKERRQ(ierr);

  /* outer congerance loop */
  for (ilev=0;ilev<=nrefine;ilev++) {
    user->ilev = ilev; /* cache needed for collecting functionals (errors) */
    if (ilev!=0) {
      for (i=0;i<mod->dim;i++) N[i] *= refinement_ratio;
    }
    for (i=0;i<mod->dim;i++) user->dx[ilev][i] = L/N[i];
    /* create base mesh */
    switch (mod->dim) {
    case 2:
      ierr = DMDACreate2d(comm, DMDA_BOUNDARY_NONE, DMDA_BOUNDARY_NONE, DMDA_STENCIL_BOX, N[0], N[1], PETSC_DETERMINE, PETSC_DETERMINE, 1, 1, NULL, NULL, &dm);CHKERRQ(ierr);
      break;
    case 3:
      ierr = DMDACreate3d(comm, DMDA_BOUNDARY_NONE, DMDA_BOUNDARY_NONE, DMDA_BOUNDARY_NONE, DMDA_STENCIL_BOX,  N[0], N[1], N[2], PETSC_DETERMINE, PETSC_DETERMINE, PETSC_DETERMINE, 1, 1, NULL, NULL, NULL, &dm);CHKERRQ(ierr);
      break;
    default:
      SETERRQ1(PETSC_COMM_SELF, PETSC_ERR_ARG_OUTOFRANGE, "Cannot create structured mesh of dimension %d", mod->dim);
    }
    ierr = DMDASetVertexCoordinates(dm, 0.0, L, 0.0, L, 0.0, L);CHKERRQ(ierr);
    PetscPrintf(PETSC_COMM_WORLD,"\t%d) N=(%d,%d,%d) dim=%d dx=(%e,%e)\n",ilev,N[0],N[1],N[2],mod->dim,user->dx[ilev][0],user->dx[ilev][1]);
    if (1){
      DM distributedMesh = NULL;
      /* Distribute mesh over processes */
      ierr = DMPlexDistribute(dm, "chaco", 0, NULL, &distributedMesh);CHKERRQ(ierr);
      if (distributedMesh) {
        ierr = DMDestroy(&dm);CHKERRQ(ierr);
        dm = distributedMesh;
      }
    }

    ierr = PetscObjectSetName((PetscObject)dm, "Coarsest Mesh");CHKERRQ(ierr);
    ierr = DMSetFromOptions(dm);CHKERRQ(ierr);
    DMView(dm,PETSC_VIEWER_STDOUT_WORLD);

    ierr = ConstructGeometry(dm, &user->facegeom, &user->cellgeom, user);CHKERRQ(ierr);
    if (1) {ierr = VecView(user->cellgeom, PETSC_VIEWER_STDOUT_WORLD);CHKERRQ(ierr);}
    /* ierr = DMPlexSetPreallocationCenterDimension(dm, 0);CHKERRQ(ierr); ??????????????? */

    /* Set up DM with section describing local vector and configure local vector. */
    /* ierr = SetUpLocalSpace(dm, user);CHKERRQ(ierr); */
    {
      PetscSection    section;
      PetscInt        numComp[1] = {1};
      PetscInt        numDof[1] = {1};
      ierr = DMDACreateSection(dm, numComp, numDof, NULL, &section);CHKERRQ(ierr);
      ierr = DMSetDefaultSection(dm, section);CHKERRQ(ierr);
      ierr = PetscSectionDestroy(&section);CHKERRQ(ierr);
    }

    ierr = DMCreateGlobalVector(dm, &X);CHKERRQ(ierr);
    ierr = SetInitialCondition(dm, X, user);CHKERRQ(ierr);

    if (vtkCellGeom) {
      DM  dmCell;
      Vec partition;

      ierr = OutputVTK(dm, "ex99-cellgeom.vtk", &viewer);CHKERRQ(ierr);
      ierr = VecView(user->cellgeom, viewer);CHKERRQ(ierr);
      ierr = PetscViewerDestroy(&viewer);CHKERRQ(ierr);
      ierr = CreatePartitionVec(dm, &dmCell, &partition);CHKERRQ(ierr);
      ierr = OutputVTK(dmCell, "ex99-partition.vtk", &viewer);CHKERRQ(ierr);
      ierr = VecView(partition, viewer);CHKERRQ(ierr);
      ierr = PetscViewerDestroy(&viewer);CHKERRQ(ierr);
      ierr = VecDestroy(&partition);CHKERRQ(ierr);
      ierr = DMDestroy(&dmCell);CHKERRQ(ierr);
    }

    ierr = DMCreateMatrix(dm, &A);CHKERRQ(ierr);
    { /* finite difference Jacobian A */
      SNES snes;
      MatStructure flag;

      ierr = SNESCreate(comm, &snes);CHKERRQ(ierr);
      ierr = SNESSetDM(snes,dm);CHKERRQ(ierr);
      ierr = SNESSetFunction(snes,NULL,ComputeFunctionLap,user);CHKERRQ(ierr);
      ierr = SNESSetJacobian(snes,A,A,SNESComputeJacobianDefaultColor,0);CHKERRQ(ierr);

      ierr = SNESComputeJacobian(snes,X,&A,&A,&flag);CHKERRQ(ierr);
      /* ierr = MatView(A,PETSC_VIEWER_STDOUT_WORLD);CHKERRQ(ierr); */
      ierr = SNESDestroy(&snes);CHKERRQ(ierr);
    }

    /* create TS */
    ierr = TSCreate(comm, &ts);CHKERRQ(ierr);
    ierr = TSSetProblemType(ts,TS_LINEAR);CHKERRQ(ierr);
    ierr = TSSetType(ts, TSBEULER);CHKERRQ(ierr);
    ierr = TSSetDM(ts, dm);CHKERRQ(ierr);
    ierr = TSMonitorSet(ts,MonitorVTK,user,NULL);CHKERRQ(ierr);
    ierr = TSSetRHSJacobian(ts,A,A,TSComputeRHSJacobianConstant,&user);CHKERRQ(ierr);
    ierr = TSSetRHSFunction(ts,NULL,RHSFunctionLap,user);CHKERRQ(ierr);
    ierr = TSSetDuration(ts,1,2.0);CHKERRQ(ierr);
    dt   = 1.e20;
    ierr = TSSetInitialTimeStep(ts,0.0,dt);CHKERRQ(ierr);
    ierr = TSSetSolution(ts,X);CHKERRQ(ierr);
    ierr = TSSetFromOptions(ts);CHKERRQ(ierr);

    /* solve */
    ierr = TSSolve(ts,X);CHKERRQ(ierr);
    ierr = TSGetSolveTime(ts,&ftime);CHKERRQ(ierr);
    ierr = TSGetTimeStepNumber(ts,&nsteps);CHKERRQ(ierr);
    ierr = TSGetConvergedReason(ts,&reason);CHKERRQ(ierr);
    PetscPrintf(PETSC_COMM_WORLD,"%s at time %G after %D steps. Errors: |e|_inf=%e |e|_2=%e, N=%d\n",TSConvergedReasons[reason],ftime,nsteps,user->errorInf[ilev],user->error2[ilev],N[0]);

    /* clean up */
    ierr = TSDestroy(&ts);CHKERRQ(ierr);
    ierr = DMDestroy(&dm);CHKERRQ(ierr);
    ierr = VecDestroy(&user->cellgeom);CHKERRQ(ierr);
    ierr = VecDestroy(&user->facegeom);CHKERRQ(ierr);
    ierr = VecDestroy(&X);CHKERRQ(ierr);
    ierr = MatDestroy(&A);CHKERRQ(ierr);
  }

  /* print out convergence rates */
  if (nrefine>0 && mod->numCall>0) {
    PetscPrintf(PETSC_COMM_WORLD,"\tN | Convergance rates |e|_inf\t\t|e|_2  (%d)\n",mod->numCall);
    for (ilev=1;ilev<=nrefine;ilev++) {
      const PetscReal log2r = 1.0/log(2.0);
      PetscReal ratio = user->errorInf[ilev-1]/user->errorInf[ilev];
      const PetscReal convergeRate_Inf = log(ratio)*log2r;
      ratio = user->error2[ilev-1]/user->error2[ilev];
      const PetscReal convergeRate_2 = log(ratio)*log2r;
      PetscPrintf(PETSC_COMM_WORLD,"\t%d\t\t\t%e\t%e\n",-1,convergeRate_Inf,convergeRate_2);
    }
  }

  ierr = FunctionalLinkDestroy(&user->model->functionalRegistry);CHKERRQ(ierr);
  ierr = PetscFree(user->model->functionalMonitored);CHKERRQ(ierr);
  ierr = PetscFree(user->model->functionalCall);CHKERRQ(ierr);
  ierr = PetscFree(user->model->physics->data);CHKERRQ(ierr);
  ierr = PetscFree(user->model->physics);CHKERRQ(ierr);
  ierr = PetscFree(user->model);CHKERRQ(ierr);
  ierr = PetscFree(user);CHKERRQ(ierr);

  /* { */
  /*   // setup interpolation */
  /*   const PetscInt nref=3; */
  /*   PetscReal targetx[nref+1],sourcex[nref+1],RCoef[nref*nref]; */
  /*   int i,j,k; */
  /*   for (i=0,j=-(nref-1)/2;i<=nref;i++,j++) targetx[i] = j; */
  /*   //  normal interpolant */
  /*   //  sources:     0             1            2           3 */
  /*   //  targets (*)  |      o      |      *     |     o     | */
  /*   //  coord       -1             0.           1           2 */
  /*   for (i=0,j=-(nref-1)/2;i<=nref;i++,j++) sourcex[i] = j; */
  /*   printf("source: "); */
  /*   for (i=0;i<=nref;i++) printf(" %e",sourcex[i]); printf("\ntargetx:"); */
  /*   for (i=0;i<=nref;i++) printf(" %e",targetx[i]); printf("\n"); */
  /*   // PetscDTReconstructPoly(degree,nsource,*sourcex,ntarget,*targetx,*R) */
  /*   ierr = PetscDTReconstructPoly(nref-1,nref,sourcex,nref,targetx,RCoef);CHKERRQ(ierr); */
  /*   for (i=0,k=0;i<nref;i++) { */
  /*     printf("RCoef:"); */
  /*     for (j=0;j<nref;j++,k++) printf(" %e",RCoef[k]); */
  /*     printf("\n"); */
  /*   } */
  /* } */

  ierr = PetscFinalize();
  return(0);
  }
