
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = newtonas.c
SOURCEF  =
SOURCEH  = newtonasimpl.h
LIBBASE  = libpetscsnes
MANSEC   = SNES
LOCDIR   = src/snes/impls/newtonas/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
