
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = newtonaugas.c
SOURCEF  =
SOURCEH  = newtonaugasimpl.h
LIBBASE  = libpetscsnes
MANSEC   = SNES
LOCDIR   = src/snes/impls/newtonaugas/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
