
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dmfieldmapped.c
SOURCEF  =
LIBBASE  = libpetscdm
DIRS     = 
LOCDIR   = src/dm/field/impls/mapped
MANSEC   = DM

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
