
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = msnes.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscmsnes
MANSEC   = SNES
DIRS     =
LOCDIR   = src/msnes/interface/

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test

