ALL: lib

CPPFLAGS =
CFLAGS   =
FFLAGS   =
SOURCEC  = networkcreate.c network.c
SOURCEF  =
SOURCEH  =
DIRS     = 
LIBBASE  = libpetscdm
MANSEC   = DM
SUBMANSEC = DMNETWORK
LOCDIR   = src/dm/impls/network/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test
