
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dmts.c dmdats.c tsrhspartition.c
SOURCEF  =
SOURCEH  =
LIBBASE  = libpetscts
MANSEC   = TS
DIRS     =
EDIRS    =
LOCDIR   = src/ts/utils/

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

