ALL: lib

CFLAGS   =
SOURCEH	 =
SOURCEC  = dlregisthreadcomm.c dlregisthreadpool.c threadcomm.c threadpoolregi.c threadcommred.c threadpool.c
LIBBASE	 = libpetscsys
DIRS	 =
LOCDIR   = src/sys/threadcomm/interface/
MANSEC   = PetscThreadComm

include ${PETSC_DIR}/conf/variables
include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/test

